---
# tasks file for mysql

 - name: install mysql server
   apt:
     name: 
     - mysql-server
     - python3-pymysql
     state: present
   become: yes

 - name: set root mysql password
   mysql_user:
     name: root
     password: "{{ mysql_root_pass }}"
     login_user: root
     login_password: "{{ mysql_root_pass }}"
     check_implicit_admin: yes
     priv: "*.*:ALL,GRANT"
     login_unix_socket: /var/run/mysqld/mysqld.sock
   become: yes

 - name: Create WP Database
   mysql_db:
     name: '{{ wp_db_name }}'
     state: present
     login_user: root
     login_password: '{{ mysql_root_pass }}'
   become: yes

 - name: Create WP mysql user
   mysql_user:
     name: '{{ wp_mysql_user }}'
     password: '{{ wp_mysql_pass }}'
     priv: '{{wp_db_name}}.*:ALL'
     login_user: root
     login_password: "{{ mysql_root_pass }}"
     state: present
   become: yes

